### ISSUE TITLE
Feature Request: `swpm ci` as alias for for `swpm install --frozen-lockfile`

### ISSUE THREAD

**Issue by AprilArcus** [deinsoftware/swpm#6]
add `swpm ci` as alias for for `swpm install --frozen-lockfile`

Use case: I want to alias `swpm` to `npm` to facilitate transitioning my monorepo to `pnpm`. `swpm` has aliases for many `npm` conventions, but not for `npm ci`.

**Comment by equiman** [comment]
Hi @AprilArcus thanks for your report.

It already works with `swpm ci`. Because you can use the [Non Documented Commands](https://github.com/deinsoftware/swpm#non-documented-commands). 

If `swpm` does not find a command to translate will run the command using the selected package manager. For example, using this command `swpm ci -use npm` it will be translated to `npm ci`. 
Or if you have defined the `npm` to be [used by default as an environment variable](https://github.com/deinsoftware/swpm#use), using this command `swpm ci` it will be translated to `npm ci`. 

But take in mind that it will only work with `npm` because the other package manager doesn't have the `ci` command. 

Let me know if that solves the issue.

**Comment by AprilArcus** [comment]
That precisely it. I'd like to alias `npm` to `swpm` so that when my users execute `swpm ci`, `pnpm install --frozen-lockfile` is executed. That way our use of `pnpm` will be an implementation detail, and we won't have to migrate all our shell scripts to `pnpm` only to migrate back when `npm` introduces the features we need.

**Comment by equiman** [comment]
Well, that is another use case that is not the core of `swpm`, because you need a direct translation between `npm` to `pnpm` and `swpm` doesn't have this feature.

One solution is to use `swpm` at the top, or maybe you can use `zsh hooks` because it can be used as an alternative to detect when an `npm` command was entered and then transform it manually with his equivalent command on `pnpm`
